# Generated by Django 5.0.2 on 2024-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybankapp', '0003_alter_useraccount_accno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='amount',
            field=models.FloatField(null=True, verbose_name='Balance'),
        ),
    ]
