# Generated by Django 5.0.2 on 2024-05-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybankapp', '0004_alter_useraccount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='accno',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
