# Generated by Django 5.0.2 on 2024-05-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybankapp', '0007_alter_useraccount_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='accno',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
